// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDocbDXJ0RnC2fk0qGINf-Yhh6xGk2dIfU',
    appId: '1:861775285204:web:c6f57596fc84d59ca7a441',
    messagingSenderId: '861775285204',
    projectId: 'duo-words-ca0ac',
    authDomain: 'duo-words-ca0ac.firebaseapp.com',
    storageBucket: 'duo-words-ca0ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7JuRqdHabQ9NUdzu8bwaoNM8eq0fsd9U',
    appId: '1:861775285204:android:091129094486e26fa7a441',
    messagingSenderId: '861775285204',
    projectId: 'duo-words-ca0ac',
    storageBucket: 'duo-words-ca0ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjRLC9FiG5xT8OHESkVO2IRxgpw942v8I',
    appId: '1:861775285204:ios:12a38ab8e811176da7a441',
    messagingSenderId: '861775285204',
    projectId: 'duo-words-ca0ac',
    storageBucket: 'duo-words-ca0ac.firebasestorage.app',
    iosBundleId: 'diogocosta.com.duoWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjRLC9FiG5xT8OHESkVO2IRxgpw942v8I',
    appId: '1:861775285204:ios:12a38ab8e811176da7a441',
    messagingSenderId: '861775285204',
    projectId: 'duo-words-ca0ac',
    storageBucket: 'duo-words-ca0ac.firebasestorage.app',
    iosBundleId: 'diogocosta.com.duoWords',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDocbDXJ0RnC2fk0qGINf-Yhh6xGk2dIfU',
    appId: '1:861775285204:web:7f6e798b6a4fed2fa7a441',
    messagingSenderId: '861775285204',
    projectId: 'duo-words-ca0ac',
    authDomain: 'duo-words-ca0ac.firebaseapp.com',
    storageBucket: 'duo-words-ca0ac.firebasestorage.app',
  );
}
